openapi: 3.0.1
info:
  title: sqlmapapi OpenAPI/Swagger specification
  version: '0.2'
paths:
  /version:
    get:
      description: Fetch server version
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "1.5.7.7#dev"
                  success:
                    type: boolean
                    example: true
  /task/new:
    get:
      description: Create a new task
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskid:
                    type: string
                    example: "fad44d6beef72285"
                  success:
                    type: boolean
                    example: true
  /scan/{taskid}/start:
    post:
      description: Launch a scan
      parameters:
        - in: path
          name: taskid
          required: true
          schema:
            type: string
          description: Scan task ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
            examples:
              '0':
                value: '{"url":"http://testphp.vulnweb.com/artists.php?artist=1"}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  engineid:
                    type: integer
                    example: 19720
                  success:
                    type: boolean
                    example: true
  /scan/{taskid}/stop:
    get:
      description: Stop a scan
      parameters:
        - in: path
          name: taskid
          required: true
          schema:
            type: string
          description: Scan task ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
  /api/tamper-history:
    get:
      description: Fetch tamper history log
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  data:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                    example:
                      Cloudflare:
                        - space2comment
                        - randomcase
                  success:
                    type: boolean
                    example: true
  /api/tamper-history/reset:
    post:
      description: Reset tamper history log
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Tamper history reset successfully"
                  success:
                    type: boolean
                    example: true
